import StreakDashboard from '../StreakDashboard';
import { type TeamWithStreak, type PlayerWithStreak } from '@shared/schema';

export default function StreakDashboardExample() {
  // todo: remove mock functionality
  const mockTeams: TeamWithStreak[] = [
    {
      id: 'man-city',
      name: 'Manchester City',
      leagueId: 'premier-league',
      recentMatches: [
        { date: '2024-01-15', result: 'W', opponent: 'Chelsea', score: '3-1', isHome: true },
        { date: '2024-01-10', result: 'W', opponent: 'Arsenal', score: '2-0', isHome: false },
        { date: '2024-01-05', result: 'W', opponent: 'Liverpool', score: '2-1', isHome: true },
        { date: '2024-01-01', result: 'W', opponent: 'Tottenham', score: '3-2', isHome: false },
        { date: '2023-12-28', result: 'W', opponent: 'Newcastle', score: '1-0', isHome: true },
        { date: '2023-12-23', result: 'W', opponent: 'Brighton', score: '4-1', isHome: true },
      ],
      nextFixture: {
        opponent: 'Wolves',
        date: '2024-01-22T15:00:00Z',
        venue: 'Etihad Stadium',
        isHome: true,
        odds: {
          bookmaker: 'Bet365',
          win: 1.35,
          draw: 5.20,
          loss: 8.50,
          doubleChance1X: 1.15,
          doubleChance12: 1.18,
          doubleChanceX2: 2.85,
        },
      },
      streakPattern: 'W-W-W-W-W',
      streakType: 'winning',
      streakDescription: '5 consecutive wins',
    },
    {
      id: 'arsenal',
      name: 'Arsenal',
      leagueId: 'premier-league',
      recentMatches: [
        { date: '2024-01-15', result: 'W', opponent: 'West Ham', score: '2-0', isHome: true },
        { date: '2024-01-10', result: 'W', opponent: 'Crystal Palace', score: '3-1', isHome: false },
        { date: '2024-01-05', result: 'W', opponent: 'Brighton', score: '1-0', isHome: true },
        { date: '2024-01-01', result: 'D', opponent: 'Liverpool', score: '1-1', isHome: false },
        { date: '2023-12-28', result: 'W', opponent: 'Luton', score: '4-3', isHome: true },
        { date: '2023-12-23', result: 'W', opponent: 'Brighton', score: '2-0', isHome: false },
      ],
      nextFixture: {
        opponent: 'Burnley',
        date: '2024-01-23T20:00:00Z',
        venue: 'Emirates Stadium',
        isHome: true,
        odds: {
          bookmaker: 'William Hill',
          win: 1.22,
          draw: 6.75,
          loss: 12.00,
          doubleChance1X: 1.08,
          doubleChance12: 1.10,
          doubleChanceX2: 3.50,
        },
      },
      streakPattern: 'W-W-W-D-W',
      streakType: 'winning',
      streakDescription: '3 wins, preceded by draw, preceded by win',
    },
    {
      id: 'real-madrid',
      name: 'Real Madrid',
      leagueId: 'la-liga',
      recentMatches: [
        { date: '2024-01-15', result: 'W', opponent: 'Barcelona', score: '3-2', isHome: true },
        { date: '2024-01-10', result: 'W', opponent: 'Atletico', score: '2-1', isHome: false },
        { date: '2024-01-05', result: 'W', opponent: 'Sevilla', score: '1-0', isHome: true },
        { date: '2024-01-01', result: 'W', opponent: 'Valencia', score: '2-0', isHome: true },
        { date: '2023-12-28', result: 'D', opponent: 'Getafe', score: '0-0', isHome: false },
        { date: '2023-12-23', result: 'W', opponent: 'Alaves', score: '3-1', isHome: true },
      ],
      nextFixture: {
        opponent: 'Athletic Bilbao',
        date: '2024-01-21T21:00:00Z',
        venue: 'Santiago Bernabéu',
        isHome: true,
        odds: {
          bookmaker: 'Betfair',
          win: 1.45,
          draw: 4.80,
          loss: 6.25,
          doubleChance1X: 1.20,
          doubleChance12: 1.22,
          doubleChanceX2: 2.60,
        },
      },
      streakPattern: 'W-W-W-W-D',
      streakType: 'winning',
      streakDescription: '4 wins preceded by 1 draw',
    },
    {
      id: 'napoli',
      name: 'Napoli',
      leagueId: 'serie-a',
      recentMatches: [
        { date: '2024-01-15', result: 'D', opponent: 'Juventus', score: '1-1', isHome: false },
        { date: '2024-01-10', result: 'D', opponent: 'Inter', score: '2-2', isHome: true },
        { date: '2024-01-05', result: 'D', opponent: 'Milan', score: '0-0', isHome: false },
        { date: '2024-01-01', result: 'D', opponent: 'Roma', score: '1-1', isHome: true },
        { date: '2023-12-28', result: 'D', opponent: 'Lazio', score: '2-2', isHome: false },
        { date: '2023-12-23', result: 'W', opponent: 'Fiorentina', score: '3-1', isHome: true },
      ],
      nextFixture: {
        opponent: 'Bologna',
        date: '2024-01-20T20:45:00Z',
        venue: 'Diego Armando Maradona Stadium',
        isHome: true,
        odds: {
          bookmaker: 'Sisal',
          win: 2.10,
          draw: 3.40,
          loss: 3.70,
          doubleChance1X: 1.35,
          doubleChance12: 1.40,
          doubleChanceX2: 1.85,
        },
      },
      streakPattern: 'D-D-D-D-D',
      streakType: 'drawing',
      streakDescription: '5 consecutive draws',
    },
    {
      id: 'bayern',
      name: 'Bayern Munich',
      leagueId: 'bundesliga',
      recentMatches: [
        { date: '2024-01-15', result: 'D', opponent: 'Dortmund', score: '2-2', isHome: true },
        { date: '2024-01-10', result: 'D', opponent: 'Leipzig', score: '1-1', isHome: false },
        { date: '2024-01-05', result: 'D', opponent: 'Leverkusen', score: '0-0', isHome: true },
        { date: '2024-01-01', result: 'W', opponent: 'Stuttgart', score: '3-0', isHome: false },
        { date: '2023-12-28', result: 'W', opponent: 'Wolfsburg', score: '2-1', isHome: true },
        { date: '2023-12-23', result: 'L', opponent: 'Frankfurt', score: '1-2', isHome: false },
      ],
      nextFixture: {
        opponent: 'Augsburg',
        date: '2024-01-22T18:30:00Z',
        venue: 'Allianz Arena',
        isHome: true,
        odds: {
          bookmaker: 'Tipico',
          win: 1.18,
          draw: 7.50,
          loss: 15.00,
          doubleChance1X: 1.06,
          doubleChance12: 1.08,
          doubleChanceX2: 3.80,
        },
      },
      streakPattern: 'D-D-D-W-W',
      streakType: 'drawing',
      streakDescription: '3 draws preceded by 2 wins',
    },
    {
      id: 'psg',
      name: 'Paris Saint-Germain',
      leagueId: 'ligue-1',
      recentMatches: [
        { date: '2024-01-15', result: 'W', opponent: 'Marseille', score: '3-0', isHome: true },
        { date: '2024-01-10', result: 'W', opponent: 'Lyon', score: '2-1', isHome: false },
        { date: '2024-01-05', result: 'W', opponent: 'Monaco', score: '2-0', isHome: true },
        { date: '2024-01-01', result: 'L', opponent: 'Nice', score: '1-2', isHome: false },
        { date: '2023-12-28', result: 'W', opponent: 'Lille', score: '3-1', isHome: true },
        { date: '2023-12-23', result: 'W', opponent: 'Rennes', score: '1-0', isHome: false },
      ],
      nextFixture: {
        opponent: 'Brest',
        date: '2024-01-21T17:00:00Z',
        venue: 'Parc des Princes',
        isHome: true,
        odds: {
          bookmaker: 'PMU',
          win: 1.28,
          draw: 6.10,
          loss: 11.50,
          doubleChance1X: 1.12,
          doubleChance12: 1.14,
          doubleChanceX2: 3.25,
        },
      },
      streakPattern: 'W-W-W-L',
      streakType: 'winning',
      streakDescription: '3 wins preceded by 1 loss',
    },
    {
      id: 'legia-warsaw',
      name: 'Legia Warsaw',
      leagueId: 'ekstraklasa',
      recentMatches: [
        { date: '2024-01-15', result: 'W', opponent: 'Rakow', score: '2-1', isHome: true },
        { date: '2024-01-10', result: 'W', opponent: 'Lech Poznan', score: '3-0', isHome: false },
        { date: '2024-01-05', result: 'W', opponent: 'Cracovia', score: '2-0', isHome: true },
        { date: '2024-01-01', result: 'L', opponent: 'Pogon', score: '0-1', isHome: false },
        { date: '2023-12-28', result: 'L', opponent: 'Jagiellonia', score: '1-2', isHome: true },
        { date: '2023-12-23', result: 'W', opponent: 'Gornik', score: '3-1', isHome: false },
      ],
      nextFixture: {
        opponent: 'Slask Wroclaw',
        date: '2024-01-21T18:00:00Z',
        venue: 'Polish Army Stadium',
        isHome: true,
        odds: {
          bookmaker: 'Fortuna',
          win: 1.65,
          draw: 3.80,
          loss: 5.20,
          doubleChance1X: 1.25,
          doubleChance12: 1.28,
          doubleChanceX2: 2.15,
        },
      },
      streakPattern: 'W-W-W-L-L',
      streakType: 'winning',
      streakDescription: '3 wins preceded by 2 losses',
    },
    {
      id: 'fcsb',
      name: 'FCSB',
      leagueId: 'liga-1-rou',
      recentMatches: [
        { date: '2024-01-15', result: 'W', opponent: 'CFR Cluj', score: '2-0', isHome: true },
        { date: '2024-01-10', result: 'W', opponent: 'Rapid', score: '1-0', isHome: false },
        { date: '2024-01-05', result: 'W', opponent: 'Craiova', score: '3-1', isHome: true },
        { date: '2024-01-01', result: 'W', opponent: 'Sepsi', score: '2-1', isHome: true },
        { date: '2023-12-28', result: 'W', opponent: 'Botosani', score: '4-0', isHome: false },
        { date: '2023-12-23', result: 'D', opponent: 'Petrolul', score: '1-1', isHome: true },
      ],
      nextFixture: {
        opponent: 'Dinamo Bucharest',
        date: '2024-01-22T19:30:00Z',
        venue: 'National Arena',
        isHome: true,
        odds: {
          bookmaker: 'Superbet',
          win: 1.40,
          draw: 4.50,
          loss: 7.80,
          doubleChance1X: 1.18,
          doubleChance12: 1.20,
          doubleChanceX2: 2.75,
        },
      },
      streakPattern: 'W-W-W-W-W',
      streakType: 'winning',
      streakDescription: '5 consecutive wins',
    },
    {
      id: 'red-star',
      name: 'Red Star Belgrade',
      leagueId: 'superliga-srb',
      recentMatches: [
        { date: '2024-01-15', result: 'D', opponent: 'Partizan', score: '1-1', isHome: true },
        { date: '2024-01-10', result: 'D', opponent: 'Vojvodina', score: '0-0', isHome: false },
        { date: '2024-01-05', result: 'D', opponent: 'Cukaricki', score: '2-2', isHome: true },
        { date: '2024-01-01', result: 'W', opponent: 'Radnicki', score: '3-0', isHome: false },
        { date: '2023-12-28', result: 'W', opponent: 'TSC', score: '2-1', isHome: true },
        { date: '2023-12-23', result: 'L', opponent: 'Novi Pazar', score: '0-1', isHome: false },
      ],
      nextFixture: {
        opponent: 'Spartak Subotica',
        date: '2024-01-20T17:00:00Z',
        venue: 'Rajko Mitic Stadium',
        isHome: true,
        odds: {
          bookmaker: 'Mozzart',
          win: 1.35,
          draw: 5.00,
          loss: 9.50,
          doubleChance1X: 1.15,
          doubleChance12: 1.18,
          doubleChanceX2: 3.10,
        },
      },
      streakPattern: 'D-D-D-W-W',
      streakType: 'drawing',
      streakDescription: '3 draws preceded by 2 wins',
    },
    {
      id: 'young-boys',
      name: 'Young Boys',
      leagueId: 'super-league-che',
      recentMatches: [
        { date: '2024-01-15', result: 'W', opponent: 'Basel', score: '3-1', isHome: true },
        { date: '2024-01-10', result: 'W', opponent: 'Servette', score: '2-0', isHome: false },
        { date: '2024-01-05', result: 'W', opponent: 'Lugano', score: '1-0', isHome: true },
        { date: '2024-01-01', result: 'D', opponent: 'St. Gallen', score: '1-1', isHome: false },
        { date: '2023-12-28', result: 'D', opponent: 'Sion', score: '0-0', isHome: true },
        { date: '2023-12-23', result: 'W', opponent: 'Grasshoppers', score: '2-1', isHome: false },
      ],
      nextFixture: {
        opponent: 'FC Zurich',
        date: '2024-01-21T15:30:00Z',
        venue: 'Wankdorf Stadium',
        isHome: true,
        odds: {
          bookmaker: 'Credit Suisse',
          win: 1.72,
          draw: 3.60,
          loss: 4.80,
          doubleChance1X: 1.28,
          doubleChance12: 1.30,
          doubleChanceX2: 2.05,
        },
      },
      streakPattern: 'W-W-W-D-D',
      streakType: 'winning',
      streakDescription: '3 wins preceded by 2 draws',
    },
    {
      id: 'colo-colo',
      name: 'Colo-Colo',
      leagueId: 'primera-division-chl',
      recentMatches: [
        { date: '2024-01-15', result: 'W', opponent: 'Universidad', score: '2-0', isHome: true },
        { date: '2024-01-10', result: 'W', opponent: 'Catolica', score: '3-1', isHome: false },
        { date: '2024-01-05', result: 'W', opponent: 'U. Espanola', score: '1-0', isHome: true },
        { date: '2024-01-01', result: 'W', opponent: 'Cobreloa', score: '2-1', isHome: false },
        { date: '2023-12-28', result: 'L', opponent: 'Huachipato', score: '0-1', isHome: true },
        { date: '2023-12-23', result: 'W', opponent: 'Everton', score: '3-0', isHome: true },
      ],
      nextFixture: {
        opponent: 'Palestino',
        date: '2024-01-23T22:00:00Z',
        venue: 'Estadio Monumental',
        isHome: true,
        odds: {
          bookmaker: 'Itau',
          win: 1.55,
          draw: 3.90,
          loss: 6.00,
          doubleChance1X: 1.22,
          doubleChance12: 1.25,
          doubleChanceX2: 2.30,
        },
      },
      streakPattern: 'W-W-W-W-L',
      streakType: 'winning',
      streakDescription: '4 wins preceded by 1 loss',
    },
  ];

  // todo: remove mock functionality
  const mockPlayers: PlayerWithStreak[] = [
    {
      id: 'erling-haaland',
      name: 'Erling Haaland',
      clubName: 'Manchester City',
      clubLogo: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
      leagueId: 'premier-league',
      position: 'FWD',
      photoUrl: 'https://example.com/haaland.jpg',
      consecutiveGoals: [
        { date: '2024-01-15', opponent: 'Chelsea', goals: 2, isHome: true },
        { date: '2024-01-10', opponent: 'Arsenal', goals: 1, isHome: false },
        { date: '2024-01-05', opponent: 'Liverpool', goals: 1, isHome: true },
        { date: '2024-01-01', opponent: 'Tottenham', goals: 2, isHome: false },
      ],
      totalGoals: 6,
      nextFixture: {
        opponent: 'Wolves',
        date: '2024-01-22T15:00:00Z',
        venue: 'Etihad Stadium',
        isHome: true,
        odds: {
          bookmaker: 'Bet365',
          win: 1.35,
          draw: 5.20,
          loss: 8.50,
          firstGoalscorer: 4.50,
          anytimeGoalscorer: 1.85,
          twoOrMoreGoals: 3.20,
        },
      },
      streakDescription: 'Scored in 4 consecutive matches (6 goals)',
      streakLength: 4,
      favoriteVictim: {
        teamName: 'Wolves',
        goalsScored: 8,
      },
    },
    {
      id: 'kylian-mbappe',
      name: 'Kylian Mbappé',
      clubName: 'Real Madrid',
      clubLogo: '🇪🇸',
      leagueId: 'la-liga',
      position: 'FWD',
      photoUrl: 'https://example.com/mbappe.jpg',
      consecutiveGoals: [
        { date: '2024-01-15', opponent: 'Barcelona', goals: 1, isHome: true },
        { date: '2024-01-10', opponent: 'Atletico', goals: 2, isHome: false },
        { date: '2024-01-05', opponent: 'Sevilla', goals: 1, isHome: true },
      ],
      totalGoals: 4,
      nextFixture: {
        opponent: 'Athletic Bilbao',
        date: '2024-01-21T21:00:00Z',
        venue: 'Santiago Bernabéu',
        isHome: true,
        odds: {
          bookmaker: 'Betfair',
          win: 1.45,
          draw: 4.80,
          loss: 6.25,
          firstGoalscorer: 3.75,
          anytimeGoalscorer: 1.65,
          twoOrMoreGoals: 2.90,
        },
      },
      streakDescription: 'Scored in 3 consecutive matches (4 goals)',
      streakLength: 3,
      favoriteVictim: {
        teamName: 'Barcelona',
        goalsScored: 6,
      },
    },
    {
      id: 'victor-osimhen',
      name: 'Victor Osimhen',
      clubName: 'Napoli',
      clubLogo: '🇮🇹',
      leagueId: 'serie-a',
      position: 'FWD',
      photoUrl: 'https://example.com/osimhen.jpg',
      consecutiveGoals: [
        { date: '2024-01-15', opponent: 'Juventus', goals: 1, isHome: false },
        { date: '2024-01-10', opponent: 'Inter', goals: 1, isHome: true },
        { date: '2024-01-05', opponent: 'Milan', goals: 2, isHome: false },
      ],
      totalGoals: 4,
      nextFixture: {
        opponent: 'Bologna',
        date: '2024-01-20T20:45:00Z',
        venue: 'Diego Armando Maradona Stadium',
        isHome: true,
        odds: {
          bookmaker: 'Sisal',
          win: 2.10,
          draw: 3.40,
          loss: 3.70,
          firstGoalscorer: 5.25,
          anytimeGoalscorer: 2.10,
          twoOrMoreGoals: 4.50,
        },
      },
      streakDescription: 'Scored in 3 consecutive matches (4 goals)',
      streakLength: 3,
      favoriteVictim: {
        teamName: 'Milan',
        goalsScored: 5,
      },
    },
    {
      id: 'tomas-pekhart',
      name: 'Tomáš Pekhart',
      clubName: 'Legia Warsaw',
      clubLogo: '🇵🇱',
      leagueId: 'ekstraklasa',
      position: 'FWD',
      photoUrl: 'https://example.com/pekhart.jpg',
      consecutiveGoals: [
        { date: '2024-01-15', opponent: 'Rakow', goals: 1, isHome: true },
        { date: '2024-01-10', opponent: 'Lech Poznan', goals: 2, isHome: false },
        { date: '2024-01-05', opponent: 'Cracovia', goals: 1, isHome: true },
      ],
      totalGoals: 4,
      nextFixture: {
        opponent: 'Slask Wroclaw',
        date: '2024-01-21T18:00:00Z',
        venue: 'Polish Army Stadium',
        isHome: true,
        odds: {
          bookmaker: 'Fortuna',
          win: 1.65,
          draw: 3.80,
          loss: 5.20,
          firstGoalscorer: 5.00,
          anytimeGoalscorer: 2.25,
          twoOrMoreGoals: 4.20,
        },
      },
      streakDescription: 'Scored in 3 consecutive matches (4 goals)',
      streakLength: 3,
      favoriteVictim: {
        teamName: 'Cracovia',
        goalsScored: 7,
      },
    },
    {
      id: 'daniel-birligea',
      name: 'Daniel Bîrligea',
      clubName: 'FCSB',
      clubLogo: '🇷🇴',
      leagueId: 'liga-1-rou',
      position: 'FWD',
      photoUrl: 'https://example.com/birligea.jpg',
      consecutiveGoals: [
        { date: '2024-01-15', opponent: 'CFR Cluj', goals: 1, isHome: true },
        { date: '2024-01-10', opponent: 'Rapid', goals: 1, isHome: false },
        { date: '2024-01-05', opponent: 'Craiova', goals: 2, isHome: true },
        { date: '2024-01-01', opponent: 'Sepsi', goals: 1, isHome: true },
      ],
      totalGoals: 5,
      nextFixture: {
        opponent: 'Dinamo Bucharest',
        date: '2024-01-22T19:30:00Z',
        venue: 'National Arena',
        isHome: true,
        odds: {
          bookmaker: 'Superbet',
          win: 1.40,
          draw: 4.50,
          loss: 7.80,
          firstGoalscorer: 4.20,
          anytimeGoalscorer: 1.90,
          twoOrMoreGoals: 3.50,
        },
      },
      streakDescription: 'Scored in 4 consecutive matches (5 goals)',
      streakLength: 4,
      favoriteVictim: {
        teamName: 'Dinamo Bucharest',
        goalsScored: 9,
      },
    },
  ];

  const lastUpdated = new Date();

  return (
    <StreakDashboard 
      teams={mockTeams}
      players={mockPlayers}
      lastUpdated={lastUpdated}
      isLoading={false}
    />
  );
}